# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Books
golden_compass = Book.create(title: "The Golden Compass", pages: 399, publishing_year: 1996)
subtle_knife = Book.create(title: "The Subtle Knife", pages: 370, publishing_year: 1997)
amber_spyglass = Book.create(title: "The Amber Spyglass", pages: 467, publishing_year: 2000)
enders_game = Book.create(title: "Ender's Game", pages: 324, publishing_year: 1985)
dune = Book.create(title: "Dune", pages: 604, publishing_year: 1965)
good_omens = Book.create(title: "Good Omens", pages: 412, publishing_year: 1990)
american_gods = Book.create(title: "American Gods", pages: 635, publishing_year: 2001)
equal_rites = Book.create(title: "Equal Rites", pages: 228, publishing_year: 1987)
between_lines = Book.create(title: "Between the Lines", pages: 353, publishing_year: 2012)
cinderella_murder = Book.create(title: "The Cinderella Murder", pages: 320, publishing_year: 2014)
hard_boiled_wonderland = Book.create(title: "Hard-Boiled Wonderland and the End of the World", pages: 225, publishing_year: 1985)
wild_sheep_chase = Book.create(title: "A Wild Sheep Chase", pages: 356, publishing_year: 1982)
kafka_on_the_shore = Book.create(title: "Kafka on the Shore", pages: 230, publishing_year: 2002)
poisonwood_bible = Book.create(title: "The Poisonwood Bible", pages: 420, publishing_year: 1998)
name_of_the_wind = Book.create(title: "The Name of the Wind", pages: 370, publishing_year: 2007)
changelings = Book.create(title: "Changelings", pages: 275, publishing_year: 2006)
neverwhere = Book.create(title: "Neverwhere", pages: 179, publishing_year: 1996)
talisman = Book.create(title: "The Talisman", pages: 150, publishing_year: 1982)
gunslinger = Book.create(title: "The Dark Tower: The Gunslinger", pages: 224, publishing_year: 1982)
casa_de_los_espiritus = Book.create(title: "Casa do los Espiritus", pages: 328, publishing_year: 1982)
sometimes_a_great_notion = Book.create(title: "Sometimes a Great Notion", pages: 479, publishing_year: 1964)


# Authors
philip_pullman = Author.create(name: "Philip Pullman")
orson_card = Author.create(name: "Orson Scott Card")
frank_herbert = Author.create(name: "Frank Herbert")
terry_pratchett = Author.create(name: "Terry Pratchett")
neil_gaiman = Author.create(name: "Neil Gaiman")
jodi_picoult = Author.create(name: "Jodi Picoult")
samantha_vanleer = Author.create(name: "Samantha van Leer")
mary_clark = Author.create(name: "Mary Higgins Clark")
alafair_burke = Author.create(name: "Alafair Burke")
haruki_murakami = Author.create(name: "Haruki Murakami")
barbara_kingsolver = Author.create(name: "Barbara Kingsolver")
patrick_rothfuss = Author.create(name: "Patrick Rothfuss")
neil_gaiman = Author.create(name: "Neil Gaiman")
anne_mccaffrey = Author.create(name: "Anne McCaffrey")
elizabeth_scarborough = Author.create(name: "Elizabeth Ann Scarborough")
isabel_allende = Author.create(name: "Isabel Allende")
ken_kesey = Author.create(name: "Ken Kesey")
stephen_king = Author.create(name: "Stephen King")
peter_straub = Author.create(name: "Peter Straub")

# Book-Authors
BookAuthor.create(book_id: golden_compass.id, author_id: philip_pullman.id)
BookAuthor.create(book_id: subtle_knife.id, author_id: philip_pullman.id)
BookAuthor.create(book_id: amber_spyglass.id, author_id: philip_pullman.id)
BookAuthor.create(book_id: enders_game.id, author_id: orson_card.id)
BookAuthor.create(book_id: dune.id, author_id: frank_herbert.id)
BookAuthor.create(book_id: good_omens.id, author_id: terry_pratchett.id)
BookAuthor.create(book_id: good_omens.id, author_id: neil_gaiman.id)
BookAuthor.create(book_id: american_gods.id, author_id: neil_gaiman.id)
BookAuthor.create(book_id: equal_rites.id, author_id: terry_pratchett.id)
BookAuthor.create(book_id: between_lines.id, author_id: jodi_picoult.id)
BookAuthor.create(book_id: between_lines.id, author_id: samantha_vanleer.id)
BookAuthor.create(book_id: cinderella_murder.id, author_id: mary_clark.id)
BookAuthor.create(book_id: cinderella_murder.id, author_id: alafair_burke.id)
BookAuthor.create(book_id: hard_boiled_wonderland.id, author_id: haruki_murakami.id)
BookAuthor.create(book_id: wild_sheep_chase.id, author_id: haruki_murakami.id)
BookAuthor.create(book_id: kafka_on_the_shore.id, author_id: haruki_murakami.id)
BookAuthor.create(book_id: poisonwood_bible.id, author_id: barbara_kingsolver.id)
BookAuthor.create(book_id: name_of_the_wind.id, author_id: patrick_rothfuss.id)
BookAuthor.create(book_id: changelings.id, author_id: anne_mccaffrey.id)
BookAuthor.create(book_id: changelings.id, author_id: elizabeth_scarborough.id)
BookAuthor.create(book_id: neverwhere.id, author_id: neil_gaiman.id)
BookAuthor.create(book_id: talisman.id, author_id: stephen_king.id)
BookAuthor.create(book_id: talisman.id, author_id: peter_straub.id)
BookAuthor.create(book_id: gunslinger.id, author_id: stephen_king.id)
BookAuthor.create(book_id: casa_de_los_espiritus.id, author_id: isabel_allende.id)
BookAuthor.create(book_id: sometimes_a_great_notion.id, author_id: ken_kesey.id)
